on:
  push:
    branches:
      - 'main'
      - 'release/*'

name: release-please

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ github.token }}
          release-type: node
  
  publish:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}

    steps:
      # The logic below handles the npm publication:
      - name: Checkout
        uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Configure NPM
        run: npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Publish Package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Assume IAM Role and Set AWS Credentials
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-duration-seconds: 900 # Adjust as needed
  
      - name: Publish build artifacts to S3
        run: |
          cd dist
          aws s3 sync . s3://transformers-workflow-engine/libs
